PKGDIR=../../..
<$PKGDIR/mkconfig


TESTS=\
	smoke.dis\

TESTTARG=\

SYSMODULES=\
	sys.m\
	draw.m\
	sh.m\

OPTMODULES=\
	opt/powerman/tap/module/t.m\
	opt/powerman/tap/module/tap.m\

MODULES=\

<$MKFILES/mktest
