<../../mkconfig

TARG=5c

OFILES=\
	cgen.$O\
	enam.$O\
	list.$O\
	mul.$O\
	peep.$O\
	pgen.$O\
	pswt.$O\
	reg.$O\
	sgen.$O\
	swt.$O\
	txt.$O\

HFILES=\
	gc.h\
	5.out.h\
	../cc/cc.h\

LIBS=cc bio 9		# order is important

BIN=$SRC/$OBJDIR/bin

<$SRC/mkfiles/mkone-$SHELLTYPE

$SRC/$OBJDIR/lib/libcc.a:
	cd ../cc
	mk $MKFLAGS install
	mk $MKFLAGS clean

%.$O: ../cc/%.c
	$CC -I. $CFLAGS ../cc/$stem.c

#enam.c:	5.out.h
#	rc mkenam
