<../mkconfig

LIB=libtk.a

OFILES=\
	ebind.$O\
	grids.$O\
	image.$O\
	packr.$O\
	panel.$O\
	parse.$O\
	utils.$O\
	varbl.$O\
	windw.$O\
	xdata.$O\

HFILES=\
	$SRC/include/tk.h\
	$SRC/include/draw.h\

default:V:	all

<mkfile-$TKSTYLE
<$SRC/mkfiles/mksyslib-$SHELLTYPE

ebind.$O:		$SRC/include/interp.h
windw.$O:	canvs.h textw.h
