<../mkconfig

LIB=libflate.a
OFILES=\
	deflate.$O\
	deflatezlib.$O\
	deflateblock.$O\
	deflatezlibblock.$O\
	inflate.$O\
	inflatezlib.$O\
	inflateblock.$O\
	inflatezlibblock.$O\
	flateerr.$O\
	crc.$O\
	adler.$O\

HFILES=\
	$SRC/include/flate.h\
	zlib.h\

<$SRC/mkfiles/mksyslib-$SHELLTYPE
