<../../mkconfig

LIB=libsec.a

# TODO get rid of the idea.c usage
#	It is used by devssl
# TODO for 9ferno tlshand.c needs auth.h. removing it for the time being.
CFILES = des.c desmodes.c desECB.c desCBC.c des3ECB.c des3CBC.c\
        aes.c aesni.c aesCBC.c aesCFB.c aesOFB.c aes_gcm.c \
        blowfish.c \
        hmac.c md5.c md5block.c md4.c sha1.c sha1block.c\
        sha2_64.c sha2_128.c sha2block64.c sha2block128.c\
        poly1305.c\
        rc4.c\
        chacha.c chachablock.c\
        salsa.c\
        genrandom.c prng.c fastrand.c nfastrand.c\
        probably_prime.c smallprimetest.c genprime.c dsaprimes.c\
        gensafeprime.c genstrongprime.c\
        rsagen.c rsafill.c rsaencrypt.c rsadecrypt.c rsaalloc.c \
        rsaprivtopub.c x509.c decodepem.c \
        eggen.c egencrypt.c egdecrypt.c egalloc.c egprivtopub.c \
        egsign.c egverify.c \
        dsagen.c dsaalloc.c dsaprivtopub.c dsasign.c dsaverify.c \
        thumb.c readcert.c \
        aes_xts.c  \
        ecc.c\
        jacobian.c\
        ripemd.c\
        dh.c\
        curve25519.c\
        curve25519_dh.c\
        pbkdf2.c\
        scrypt.c\
        hkdf.c\
        ccpoly.c\
        tsmemcmp.c\
        secp256r1.c\
        secp384r1.c\
        secp256k1.c\
	idea.c\


ALLOFILES=${CFILES:%.c=%.$O}

# cull things in the per-machine directories from this list
OFILES=	`{$SHELLNAME ./reduce-$SHELLTYPE $O $TARGMODEL-$OBJTYPE $ALLOFILES }

HFILES=\
	$ROOT/include/libsec.h\
	$ROOT/libmp/port/os.h\

CFLAGS=$CFLAGS -I../../libmp/port

UPDATE=mkfile\
	$HFILES\
	$CFILES\

%.c:D:  %.mp
	echo '#include "os.h"' > $target
	echo '#include <mp.h>' >> $target
	mpc $prereq >> $target

# TODO fix the compile errors
#$O.rsatest: rsatest.$O
#	$LD -o $target $prereq

$O.chachatest: chachatest.$O
	$LD -o $target $prereq

$O.aesgcmtest: aesgcmtest.$O
	$LD -o $target $prereq

<$ROOT/mkfiles/mksyslib-$SHELLTYPE
