#!/bin/sh
mkd() {
	mkdir -p $1
}

mkd acme/dis
mkd dis/acme
#mkd dis/alphabet
#mkd dis/alphabet/abc
#mkd dis/alphabet/fs
#mkd dis/alphabet/grid
#mkd dis/alphabet/main
#mkd dis/alphabet/auth
#mkd dis/alphabet/auth/proto
mkd dis/auth/proto
mkd dis/auxi
mkd dis/avr
mkd dis/charon
#mkd dis/collab
#mkd dis/collab/clients
#mkd dis/collab/lib
#mkd dis/collab/servers
#mkd dis/db
mkd dis/demo
mkd dis/demo/camera
mkd dis/demo/chat
mkd dis/demo/cpupool
mkd dis/demo/lego
mkd dis/demo/ns
mkd dis/demo/odbc
mkd dis/demo/spree
mkd dis/demo/whiteboard
mkd dis/disk
#mkd dis/ebook
mkd dis/fs
mkd dis/games
mkd dis/grid
mkd dis/grid/demo
mkd dis/grid/lib
mkd dis/install
mkd dis/ip
mkd dis/ip/nppp
mkd dis/ip/ppp
mkd dis/lego
mkd dis/lib
mkd dis/lib/convcs
mkd dis/lib/crypt
mkd dis/lib/encoding
mkd dis/lib/ftree
mkd dis/lib/ida
mkd dis/lib/mash
mkd dis/lib/print
mkd dis/lib/spki
mkd dis/lib/strokes
mkd dis/lib/styxconv
mkd dis/lib/usb
mkd dis/lib/w3c
mkd dis/math
mkd dis/mpc
mkd dis/mpeg
mkd dis/ndb
#mkd dis/palm
mkd dis/sh
mkd dis/spki
#mkd dis/spree
#mkd dis/spree/clients
#mkd dis/spree/engines
#mkd dis/spree/lib
mkd dis/svc/httpd
mkd dis/svc/webget
mkd dis/tiny
mkd dis/usb
mkd dis/wm
mkd dis/wm/brutus
mkd dis/wm/vixen
mkd dis/zip
