#!/dis/sh
# If used with `run /dis/engridden`, will load public grid resources into the current namespace
# Tailored to 9p.zone 
# In loving memory of Mycroftiv's Public Grid Project
load std

# Pending a better registry method or otherwise
mount -Ac tcp!registry.9p.zone!registry /mnt/registry
mount -Ac tcp!chat.9p.zone!9990 /n/chat
mount -Ac tcp!9p.zone!9991 /n/griddisk
