#!/dis/sh
# Initialise stub directories that may be missing in the base install
# Opt material courtesy of powerman
user=`{cat /dev/user}
home=/usr/$user
dirs=($home/keyring /tmp /mnt/keys /mnt/registry /mnt/acme /n/remote /chan /keydb)

mkdir -p $home
cp -r /usr/inferno/* $home/

for i in $dirs {
	mkdir -p $i
}

