#!/dis/sh
# Initialise stub directories that may be missing in the base install
# Opt material courtesy of powerman
load std

user=`{cat /dev/user}

dis=`{cat /lib/emptydirs}

for i in $dirs {
	mkdir -p $i
}

/dis/newuser $user
