#!/dis/sh
# Initialise directories and files for a new user
load std

args = $*
argv0 = $0
user = $1

fn usage {
		echo >[1=2] usage: $argv0 username
		exit usage
}

if {! ~ $#args 1} {
	usage
}

user=$1
home=/usr/$user

dirs=($home/keyring $home/dis $home/module)

mkdir -p $home
cp -r /usr/inferno/* $home/

for i in $dirs {
	mkdir -p $i
}
