<../mkconfig

LIB=libprefab.a

OFILES=\
	box.$O\
	compound.$O\
	element.$O\
	elistelement.$O\
	iconbox.$O\
	iconelement.$O\
	textbox.$O\
	textelement.$O\

HFILES=\
	$SRC/include/draw.h\
	$SRC/include/prefab.h\

<$SRC/mkfiles/mksyslib-$SHELLTYPE

$OFILES:	$SRC/module/prefab.m
