<../../mkconfig

TARG=sed

OFILES=	sed.$O\

HFILES= $SRC/include/bio.h\
	../include/regexp.h\

LIBS=regexp bio 9		# libbio.a uses lib9.a so order matters.

CFLAGS=$CFLAGS -I../include

BIN=$SRC/$OBJDIR/bin

<$SRC/mkfiles/mkone-$SHELLTYPE
