<../../../mkconfig

TARG=\
	lszip.dis\
	getzip.dis\
	putzip.dis\
	zipfs.dis\
	zipstream.dis\

SYSMODULES=\
	arg.m\
	bufio.m\
	convcs.m\
	daytime.m\
	draw.m\
	encoding.m\
	filter.m\
	lists.m\
	string.m\
	styx.m\
	styxservers.m\
	sys.m\
	tables.m\
	zip.m\

DISBIN=$ROOT/dis/zip

<$SRC/mkfiles/mkdis
