<../../mkconfig
CFLAGS=$CFLAGS -I../include

TARG=ms2

OFILES=	ms2.$O\

HFILES=	\
	$SRC/include/bio.h\
	../include/mach.h\

LIBS=mach bio 9			#order matters

BIN=$SRC/$OBJDIR/bin

<$SRC/mkfiles/mkone-$SHELLTYPE
