#!/dis/sh

load std
# this is the most generic boot script when booting from the cd
#	sets up the network with dhcp and is done

<>/net/ipifc/clone {
	x=`{read}
	echo bind ether /net/ether0 > /net/ipifc/^$x^/ctl
}
ip/dhcp -p /net/ipifc/$x

# Networking
ndb/dns -r
ndb/cs
#bind -a '#scs' /net
