objtype=amd64
OBJTYPE=$objtype
<../../mkconfig

LIB=libmp.a
SFILES=\
	mpvecadd.s\
	mpvecdigmuladd.s\
	mpvecdigmulsub.s\
	mpvecsub.s\
	mpdigdiv.s\

HFILES=$SRC/Inferno/$OBJTYPE/include/u.h $SRC/include/mp.h ../port/dat.h

OFILES=${SFILES:%.s=%.$O}

UPDATE=mkfile\
	$HFILES\
	$SFILES\

<$SRC/mkfiles/mksyslib-$SHELLTYPE
