<../mkconfig

all:V:	all-$HOSTMODEL

install:V:	install-$HOSTMODEL
	
safeinstall:V:	safeinstall-$HOSTMODEL
clean:V:	clean-$HOSTMODEL
nuke:V:	nuke-$HOSTMODEL

&-Posix:QV:
	echo "(cd $SYSTARG; mk $MKFLAGS $stem)"
	(cd $SYSTARG; mk $MKFLAGS $stem) || exit 1

&-Nt:QV:
	echo 'cd $SYSTARG && mk $MKFLAGS $stem'
	cd MinGW && mk $MKFLAGS $stem

install-Nt:QV:
	(cd $SYSTARG && mk SHELLTYPE=sh SYSTARG=$SYSTARG OBJTYPE=$OBJTYPE i$CONF.exe) || exit 1
	cp $SYSTARG/i$CONF.exe $ROOT/$SYSTARG/$OBJTYPE/bin/$CONF.exe
	if test "x$DOSTRIP" = xyes; then \
		strip $ROOT/$SYSTARG/$OBJTYPE/bin/$CONF.exe || exit 1; \
	fi
	if test "x$DOUPX" = xyes && command -v upx >/dev/null 2>&1; then \
		upx --best --lzma $ROOT/$SYSTARG/$OBJTYPE/bin/$CONF.exe || exit 1; \
	fi

safeinstall-Nt:QV:
	(cd $SYSTARG && mk SHELLTYPE=sh SYSTARG=$SYSTARG OBJTYPE=$OBJTYPE i$CONF.exe) || exit 1
	test -f $ROOT/$SYSTARG/$OBJTYPE/bin/$CONF.exe || cp $SYSTARG/i$CONF.exe $ROOT/$SYSTARG/$OBJTYPE/bin/$CONF.exe
	if test "x$DOSTRIP" = xyes; then \
		strip $ROOT/$SYSTARG/$OBJTYPE/bin/$CONF.exe || exit 1; \
	fi
	if test "x$DOUPX" = xyes && command -v upx >/dev/null 2>&1; then \
		upx --best --lzma $ROOT/$SYSTARG/$OBJTYPE/bin/$CONF.exe || exit 1; \
	fi

clean-Nt:QV:
	cd $SYSTARG && mk $MKFLAGS clean

nuke-Nt:QV:
	cd $SYSTARG && mk $MKFLAGS nuke

&-Plan9:QV:
	echo '@{builtin cd' $SYSTARG '; mk $MKFLAGS $stem}'
	@{builtin cd $SYSTARG; mk $MKFLAGS $stem }

&-9front:QV:
	echo '@{builtin cd' $SYSTARG '; mk $MKFLAGS $stem}'
	@{builtin cd $SYSTARG; mk $MKFLAGS $stem }
