<../../../mkconfig

TARG=\
	farm.dis\
	line2rec.dis\
	local.dis\
	remote.dis\
	rexec.dis\

SYSMODULES=\
	draw.m\
	alphabet/endpoints.m\
	alphabet/grid.m\
	alphabet/reports.m\
	sh.m\
	string.m\
	sys.m\

DISBIN=$ROOT/dis/alphabet/grid

<$SRC/mkfiles/mkdis
LIMBOFLAGS=-F $LIMBOFLAGS
