<../mkconfig

LIB=libbio.a
OFILES=\
	bbuffered.$O\
	bfildes.$O\
	bflush.$O\
	bgetrune.$O\
	bgetc.$O\
	bgetd.$O\
	binit.$O\
	boffset.$O\
	bprint.$O\
	bputrune.$O\
	bputc.$O\
	brdline.$O\
	brdstr.$O\
	bread.$O\
	bseek.$O\
	bvprint.$O\
	bwrite.$O\

HFILES=	$SRC/include/bio.h

<$SRC/mkfiles/mksyslib-$SHELLTYPE
