<../mkconfig

LIB=libkeyring.a

OFILES=\
	dsaalg.$O\
	egalg.$O\
	rsaalg.$O

HFILES=\
	$SRC/include/mp.h\
	$SRC/include/libsec.h\
	$SRC/libinterp/runt.h\
	$SRC/include/interp.h\
	keys.h\

<$SRC/mkfiles/mksyslib-$SHELLTYPE
