<../../mkconfig
CFLAGS=$CFLAGS -I../include

TARG=sqz

OFILES=	sqz.$O\

HFILES=	\
	squeeze.h\
	../include/a.out.h\
	../include/mach.h\

LIBS=	mach bio 9

BIN=$SRC/$OBJDIR/bin

<$SRC/mkfiles/mkone-$SHELLTYPE

CFLAGS=	$CFLAGS -I../include
