objtype=386
OBJTYPE=$objtype
<../../mkconfig

LIB=libsec.a
FILES=\
	md5block\
	sha1block\

HFILES=$SRC/include/libsec.h

SFILES=${FILES:%=%.s}

OFILES=${FILES:%=%.$O}

<$SRC/mkfiles/mksyslib-$SHELLTYPE
