objtype=386
OBJTYPE=$objtype
<../../mkconfig

LIB=libsec.a
FILES=\
        chachablock\
        md5block\
        sha1block\
        aesni\


HFILES=$ROOT/include/libsec.h

SFILES=${FILES:%=%.s}

OFILES=${FILES:%=%.$O}

<$ROOT/mkfiles/mksyslib-$SHELLTYPE
