#!/dis/sh.dis
load std
or {ftest -e /net/dns} {ftest -e /env/emuhost} {ndb/dns}
or {ftest -e /net/cs} {ndb/cs}
or {ftest -e /mnt/factotum/ctl}  {auth/factotum; auth/feedkey}
mkdir -p /mnt/irc/freenode
mount {ircfs -a net!irc.freenode.net!6667 -n ircfsuser freenode } /mnt/irc/freenode
wm/irc /mnt/irc/freenode

kill -g Ircfs
