<../../../mkconfig

DIRS=\
	ppp\
#	nppp\

TARG=\
	bootpd.dis\
	dhcp.dis\
	dhcpd.dis\
	netaddr.dis\
	ping.dis\
	rip.dis\
	tftpd.dis\
	virgild.dis\
	sntp.dis\

SYSMODULES=\
	arg.m\
	attrdb.m\
	bufio.m\
	daytime.m\
	dhcpclient.m\
	dhcpserver.m\
	draw.m\
	encoding.m\
	ether.m\
	ip.m\
	ipattr.m\
	lists.m\
	string.m\
	sys.m\

DISBIN=$ROOT/dis/ip

<$ROOT/mkfiles/mkdis
<$ROOT/mkfiles/mksubdirs
